spring:
  datasource:
    url: jdbc:mysql://10.9.50.203:3306/ishop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver