spring:
  redis:
    database: 1
    host: 10.9.50.26
    password: redis
    port: 6379
    pool:
      max-idle: 5
      min-idle: 0
      max-active: 5
      max-wait: -1
  data:
    redis:
      repositories:
        enable: false
  session:
    store-type: redis